/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedRaporlarRouteImport } from './routes/_authenticated.raporlar'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated.profil'
import { Route as AuthenticatedOgretmenlerRouteImport } from './routes/_authenticated.ogretmenler'
import { Route as AuthenticatedOgrencilerRouteImport } from './routes/_authenticated.ogrenciler'
import { Route as AuthenticatedKurslarRouteImport } from './routes/_authenticated.kurslar'
import { Route as AuthenticatedKayitlarRouteImport } from './routes/_authenticated.kayitlar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRaporlarRoute = AuthenticatedRaporlarRouteImport.update({
  id: '/raporlar',
  path: '/raporlar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOgretmenlerRoute =
  AuthenticatedOgretmenlerRouteImport.update({
    id: '/ogretmenler',
    path: '/ogretmenler',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOgrencilerRoute = AuthenticatedOgrencilerRouteImport.update({
  id: '/ogrenciler',
  path: '/ogrenciler',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKurslarRoute = AuthenticatedKurslarRouteImport.update({
  id: '/kurslar',
  path: '/kurslar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKayitlarRoute = AuthenticatedKayitlarRouteImport.update({
  id: '/kayitlar',
  path: '/kayitlar',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kayitlar': typeof AuthenticatedKayitlarRoute
  '/kurslar': typeof AuthenticatedKurslarRoute
  '/ogrenciler': typeof AuthenticatedOgrencilerRoute
  '/ogretmenler': typeof AuthenticatedOgretmenlerRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/raporlar': typeof AuthenticatedRaporlarRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kayitlar': typeof AuthenticatedKayitlarRoute
  '/kurslar': typeof AuthenticatedKurslarRoute
  '/ogrenciler': typeof AuthenticatedOgrencilerRoute
  '/ogretmenler': typeof AuthenticatedOgretmenlerRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/raporlar': typeof AuthenticatedRaporlarRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/kayitlar': typeof AuthenticatedKayitlarRoute
  '/_authenticated/kurslar': typeof AuthenticatedKurslarRoute
  '/_authenticated/ogrenciler': typeof AuthenticatedOgrencilerRoute
  '/_authenticated/ogretmenler': typeof AuthenticatedOgretmenlerRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/raporlar': typeof AuthenticatedRaporlarRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/kayitlar'
    | '/kurslar'
    | '/ogrenciler'
    | '/ogretmenler'
    | '/profil'
    | '/raporlar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/kayitlar'
    | '/kurslar'
    | '/ogrenciler'
    | '/ogretmenler'
    | '/profil'
    | '/raporlar'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/_authenticated/kayitlar'
    | '/_authenticated/kurslar'
    | '/_authenticated/ogrenciler'
    | '/_authenticated/ogretmenler'
    | '/_authenticated/profil'
    | '/_authenticated/raporlar'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/raporlar': {
      id: '/_authenticated/raporlar'
      path: '/raporlar'
      fullPath: '/raporlar'
      preLoaderRoute: typeof AuthenticatedRaporlarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ogretmenler': {
      id: '/_authenticated/ogretmenler'
      path: '/ogretmenler'
      fullPath: '/ogretmenler'
      preLoaderRoute: typeof AuthenticatedOgretmenlerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ogrenciler': {
      id: '/_authenticated/ogrenciler'
      path: '/ogrenciler'
      fullPath: '/ogrenciler'
      preLoaderRoute: typeof AuthenticatedOgrencilerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kurslar': {
      id: '/_authenticated/kurslar'
      path: '/kurslar'
      fullPath: '/kurslar'
      preLoaderRoute: typeof AuthenticatedKurslarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kayitlar': {
      id: '/_authenticated/kayitlar'
      path: '/kayitlar'
      fullPath: '/kayitlar'
      preLoaderRoute: typeof AuthenticatedKayitlarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedKayitlarRoute: typeof AuthenticatedKayitlarRoute
  AuthenticatedKurslarRoute: typeof AuthenticatedKurslarRoute
  AuthenticatedOgrencilerRoute: typeof AuthenticatedOgrencilerRoute
  AuthenticatedOgretmenlerRoute: typeof AuthenticatedOgretmenlerRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRaporlarRoute: typeof AuthenticatedRaporlarRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedKayitlarRoute: AuthenticatedKayitlarRoute,
  AuthenticatedKurslarRoute: AuthenticatedKurslarRoute,
  AuthenticatedOgrencilerRoute: AuthenticatedOgrencilerRoute,
  AuthenticatedOgretmenlerRoute: AuthenticatedOgretmenlerRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRaporlarRoute: AuthenticatedRaporlarRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
