/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedYardimTaleplerimRouteImport } from './routes/_authenticated.yardim-taleplerim'
import { Route as AuthenticatedYardimRouteImport } from './routes/_authenticated.yardim'
import { Route as AuthenticatedVerdigimKurslarRouteImport } from './routes/_authenticated.verdigim-kurslar'
import { Route as AuthenticatedRaporlarRouteImport } from './routes/_authenticated.raporlar'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated.profil'
import { Route as AuthenticatedOgretmenlerRouteImport } from './routes/_authenticated.ogretmenler'
import { Route as AuthenticatedOgrencilerRouteImport } from './routes/_authenticated.ogrenciler'
import { Route as AuthenticatedKurslarimRouteImport } from './routes/_authenticated.kurslarim'
import { Route as AuthenticatedKurslarRouteImport } from './routes/_authenticated.kurslar'
import { Route as AuthenticatedKayitlarRouteImport } from './routes/_authenticated.kayitlar'
import { Route as AuthenticatedIsteklerRouteImport } from './routes/_authenticated.istekler'
import { Route as AuthenticatedDuyurularRouteImport } from './routes/_authenticated.duyurular'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAyarlarRouteImport } from './routes/_authenticated.ayarlar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYardimTaleplerimRoute =
  AuthenticatedYardimTaleplerimRouteImport.update({
    id: '/yardim-taleplerim',
    path: '/yardim-taleplerim',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedYardimRoute = AuthenticatedYardimRouteImport.update({
  id: '/yardim',
  path: '/yardim',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVerdigimKurslarRoute =
  AuthenticatedVerdigimKurslarRouteImport.update({
    id: '/verdigim-kurslar',
    path: '/verdigim-kurslar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRaporlarRoute = AuthenticatedRaporlarRouteImport.update({
  id: '/raporlar',
  path: '/raporlar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOgretmenlerRoute =
  AuthenticatedOgretmenlerRouteImport.update({
    id: '/ogretmenler',
    path: '/ogretmenler',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOgrencilerRoute = AuthenticatedOgrencilerRouteImport.update({
  id: '/ogrenciler',
  path: '/ogrenciler',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKurslarimRoute = AuthenticatedKurslarimRouteImport.update({
  id: '/kurslarim',
  path: '/kurslarim',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKurslarRoute = AuthenticatedKurslarRouteImport.update({
  id: '/kurslar',
  path: '/kurslar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKayitlarRoute = AuthenticatedKayitlarRouteImport.update({
  id: '/kayitlar',
  path: '/kayitlar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIsteklerRoute = AuthenticatedIsteklerRouteImport.update({
  id: '/istekler',
  path: '/istekler',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDuyurularRoute = AuthenticatedDuyurularRouteImport.update({
  id: '/duyurular',
  path: '/duyurular',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAyarlarRoute = AuthenticatedAyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ayarlar': typeof AuthenticatedAyarlarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duyurular': typeof AuthenticatedDuyurularRoute
  '/istekler': typeof AuthenticatedIsteklerRoute
  '/kayitlar': typeof AuthenticatedKayitlarRoute
  '/kurslar': typeof AuthenticatedKurslarRoute
  '/kurslarim': typeof AuthenticatedKurslarimRoute
  '/ogrenciler': typeof AuthenticatedOgrencilerRoute
  '/ogretmenler': typeof AuthenticatedOgretmenlerRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/raporlar': typeof AuthenticatedRaporlarRoute
  '/verdigim-kurslar': typeof AuthenticatedVerdigimKurslarRoute
  '/yardim': typeof AuthenticatedYardimRoute
  '/yardim-taleplerim': typeof AuthenticatedYardimTaleplerimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ayarlar': typeof AuthenticatedAyarlarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duyurular': typeof AuthenticatedDuyurularRoute
  '/istekler': typeof AuthenticatedIsteklerRoute
  '/kayitlar': typeof AuthenticatedKayitlarRoute
  '/kurslar': typeof AuthenticatedKurslarRoute
  '/kurslarim': typeof AuthenticatedKurslarimRoute
  '/ogrenciler': typeof AuthenticatedOgrencilerRoute
  '/ogretmenler': typeof AuthenticatedOgretmenlerRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/raporlar': typeof AuthenticatedRaporlarRoute
  '/verdigim-kurslar': typeof AuthenticatedVerdigimKurslarRoute
  '/yardim': typeof AuthenticatedYardimRoute
  '/yardim-taleplerim': typeof AuthenticatedYardimTaleplerimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/ayarlar': typeof AuthenticatedAyarlarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/duyurular': typeof AuthenticatedDuyurularRoute
  '/_authenticated/istekler': typeof AuthenticatedIsteklerRoute
  '/_authenticated/kayitlar': typeof AuthenticatedKayitlarRoute
  '/_authenticated/kurslar': typeof AuthenticatedKurslarRoute
  '/_authenticated/kurslarim': typeof AuthenticatedKurslarimRoute
  '/_authenticated/ogrenciler': typeof AuthenticatedOgrencilerRoute
  '/_authenticated/ogretmenler': typeof AuthenticatedOgretmenlerRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/raporlar': typeof AuthenticatedRaporlarRoute
  '/_authenticated/verdigim-kurslar': typeof AuthenticatedVerdigimKurslarRoute
  '/_authenticated/yardim': typeof AuthenticatedYardimRoute
  '/_authenticated/yardim-taleplerim': typeof AuthenticatedYardimTaleplerimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/ayarlar'
    | '/dashboard'
    | '/duyurular'
    | '/istekler'
    | '/kayitlar'
    | '/kurslar'
    | '/kurslarim'
    | '/ogrenciler'
    | '/ogretmenler'
    | '/profil'
    | '/raporlar'
    | '/verdigim-kurslar'
    | '/yardim'
    | '/yardim-taleplerim'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/ayarlar'
    | '/dashboard'
    | '/duyurular'
    | '/istekler'
    | '/kayitlar'
    | '/kurslar'
    | '/kurslarim'
    | '/ogrenciler'
    | '/ogretmenler'
    | '/profil'
    | '/raporlar'
    | '/verdigim-kurslar'
    | '/yardim'
    | '/yardim-taleplerim'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/sitemap.xml'
    | '/_authenticated/ayarlar'
    | '/_authenticated/dashboard'
    | '/_authenticated/duyurular'
    | '/_authenticated/istekler'
    | '/_authenticated/kayitlar'
    | '/_authenticated/kurslar'
    | '/_authenticated/kurslarim'
    | '/_authenticated/ogrenciler'
    | '/_authenticated/ogretmenler'
    | '/_authenticated/profil'
    | '/_authenticated/raporlar'
    | '/_authenticated/verdigim-kurslar'
    | '/_authenticated/yardim'
    | '/_authenticated/yardim-taleplerim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/yardim-taleplerim': {
      id: '/_authenticated/yardim-taleplerim'
      path: '/yardim-taleplerim'
      fullPath: '/yardim-taleplerim'
      preLoaderRoute: typeof AuthenticatedYardimTaleplerimRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/yardim': {
      id: '/_authenticated/yardim'
      path: '/yardim'
      fullPath: '/yardim'
      preLoaderRoute: typeof AuthenticatedYardimRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/verdigim-kurslar': {
      id: '/_authenticated/verdigim-kurslar'
      path: '/verdigim-kurslar'
      fullPath: '/verdigim-kurslar'
      preLoaderRoute: typeof AuthenticatedVerdigimKurslarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/raporlar': {
      id: '/_authenticated/raporlar'
      path: '/raporlar'
      fullPath: '/raporlar'
      preLoaderRoute: typeof AuthenticatedRaporlarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ogretmenler': {
      id: '/_authenticated/ogretmenler'
      path: '/ogretmenler'
      fullPath: '/ogretmenler'
      preLoaderRoute: typeof AuthenticatedOgretmenlerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ogrenciler': {
      id: '/_authenticated/ogrenciler'
      path: '/ogrenciler'
      fullPath: '/ogrenciler'
      preLoaderRoute: typeof AuthenticatedOgrencilerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kurslarim': {
      id: '/_authenticated/kurslarim'
      path: '/kurslarim'
      fullPath: '/kurslarim'
      preLoaderRoute: typeof AuthenticatedKurslarimRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kurslar': {
      id: '/_authenticated/kurslar'
      path: '/kurslar'
      fullPath: '/kurslar'
      preLoaderRoute: typeof AuthenticatedKurslarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kayitlar': {
      id: '/_authenticated/kayitlar'
      path: '/kayitlar'
      fullPath: '/kayitlar'
      preLoaderRoute: typeof AuthenticatedKayitlarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/istekler': {
      id: '/_authenticated/istekler'
      path: '/istekler'
      fullPath: '/istekler'
      preLoaderRoute: typeof AuthenticatedIsteklerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/duyurular': {
      id: '/_authenticated/duyurular'
      path: '/duyurular'
      fullPath: '/duyurular'
      preLoaderRoute: typeof AuthenticatedDuyurularRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ayarlar': {
      id: '/_authenticated/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AuthenticatedAyarlarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAyarlarRoute: typeof AuthenticatedAyarlarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDuyurularRoute: typeof AuthenticatedDuyurularRoute
  AuthenticatedIsteklerRoute: typeof AuthenticatedIsteklerRoute
  AuthenticatedKayitlarRoute: typeof AuthenticatedKayitlarRoute
  AuthenticatedKurslarRoute: typeof AuthenticatedKurslarRoute
  AuthenticatedKurslarimRoute: typeof AuthenticatedKurslarimRoute
  AuthenticatedOgrencilerRoute: typeof AuthenticatedOgrencilerRoute
  AuthenticatedOgretmenlerRoute: typeof AuthenticatedOgretmenlerRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRaporlarRoute: typeof AuthenticatedRaporlarRoute
  AuthenticatedVerdigimKurslarRoute: typeof AuthenticatedVerdigimKurslarRoute
  AuthenticatedYardimRoute: typeof AuthenticatedYardimRoute
  AuthenticatedYardimTaleplerimRoute: typeof AuthenticatedYardimTaleplerimRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAyarlarRoute: AuthenticatedAyarlarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDuyurularRoute: AuthenticatedDuyurularRoute,
  AuthenticatedIsteklerRoute: AuthenticatedIsteklerRoute,
  AuthenticatedKayitlarRoute: AuthenticatedKayitlarRoute,
  AuthenticatedKurslarRoute: AuthenticatedKurslarRoute,
  AuthenticatedKurslarimRoute: AuthenticatedKurslarimRoute,
  AuthenticatedOgrencilerRoute: AuthenticatedOgrencilerRoute,
  AuthenticatedOgretmenlerRoute: AuthenticatedOgretmenlerRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRaporlarRoute: AuthenticatedRaporlarRoute,
  AuthenticatedVerdigimKurslarRoute: AuthenticatedVerdigimKurslarRoute,
  AuthenticatedYardimRoute: AuthenticatedYardimRoute,
  AuthenticatedYardimTaleplerimRoute: AuthenticatedYardimTaleplerimRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
