/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RaporlarRouteImport } from './routes/raporlar'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as OgrencilerRouteImport } from './routes/ogrenciler'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KurslarRouteImport } from './routes/kurslar'
import { Route as KayitlarRouteImport } from './routes/kayitlar'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RaporlarRoute = RaporlarRouteImport.update({
  id: '/raporlar',
  path: '/raporlar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const OgrencilerRoute = OgrencilerRouteImport.update({
  id: '/ogrenciler',
  path: '/ogrenciler',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KurslarRoute = KurslarRouteImport.update({
  id: '/kurslar',
  path: '/kurslar',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitlarRoute = KayitlarRouteImport.update({
  id: '/kayitlar',
  path: '/kayitlar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kayitlar': typeof KayitlarRoute
  '/kurslar': typeof KurslarRoute
  '/login': typeof LoginRoute
  '/ogrenciler': typeof OgrencilerRoute
  '/profil': typeof ProfilRoute
  '/raporlar': typeof RaporlarRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kayitlar': typeof KayitlarRoute
  '/kurslar': typeof KurslarRoute
  '/login': typeof LoginRoute
  '/ogrenciler': typeof OgrencilerRoute
  '/profil': typeof ProfilRoute
  '/raporlar': typeof RaporlarRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kayitlar': typeof KayitlarRoute
  '/kurslar': typeof KurslarRoute
  '/login': typeof LoginRoute
  '/ogrenciler': typeof OgrencilerRoute
  '/profil': typeof ProfilRoute
  '/raporlar': typeof RaporlarRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kayitlar'
    | '/kurslar'
    | '/login'
    | '/ogrenciler'
    | '/profil'
    | '/raporlar'
    | '/register'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kayitlar'
    | '/kurslar'
    | '/login'
    | '/ogrenciler'
    | '/profil'
    | '/raporlar'
    | '/register'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/kayitlar'
    | '/kurslar'
    | '/login'
    | '/ogrenciler'
    | '/profil'
    | '/raporlar'
    | '/register'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KayitlarRoute: typeof KayitlarRoute
  KurslarRoute: typeof KurslarRoute
  LoginRoute: typeof LoginRoute
  OgrencilerRoute: typeof OgrencilerRoute
  ProfilRoute: typeof ProfilRoute
  RaporlarRoute: typeof RaporlarRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raporlar': {
      id: '/raporlar'
      path: '/raporlar'
      fullPath: '/raporlar'
      preLoaderRoute: typeof RaporlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ogrenciler': {
      id: '/ogrenciler'
      path: '/ogrenciler'
      fullPath: '/ogrenciler'
      preLoaderRoute: typeof OgrencilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurslar': {
      id: '/kurslar'
      path: '/kurslar'
      fullPath: '/kurslar'
      preLoaderRoute: typeof KurslarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayitlar': {
      id: '/kayitlar'
      path: '/kayitlar'
      fullPath: '/kayitlar'
      preLoaderRoute: typeof KayitlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KayitlarRoute: KayitlarRoute,
  KurslarRoute: KurslarRoute,
  LoginRoute: LoginRoute,
  OgrencilerRoute: OgrencilerRoute,
  ProfilRoute: ProfilRoute,
  RaporlarRoute: RaporlarRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
